### PR TITLE
Add bio for patann1

### LINKED ISSUE #10: Add a bio for patann1
- [x] create a branch
- [x] createa patann1.md file
- [x] open a pull request
- [x] get and receive feedback
- [x] merge the pull request

### PR DESCRIPTION
**Pull request by patann1**
Closes #10 - request for patann1, this pull request provides

### CODE REVIEW

**Comment by chauhpriya** [comment]
Please add little more detail

**Comment by patann1** [comment]
how does this look now

**Comment by chauhpriya** [comment]
GTG

**Comment by chauhpriya** [comment]
:+1: smiley: +1

**Pull request merged**
